#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Python 3.5
__author__ = "Liu jiang"

def print_list(a):
    for i in a:
        if i == 0:
            print("%-4s" % " ", end="")
        else:
            print("%-4s" % i, end="")
    print("\n")


def yh(n):
    a = [0 for i in range(2 * n + 1)]
    a[n] = 1
    k = n
    while k > 0:
        print_list(a)
        b = [0 for i in range(2 * n + 1)]
        for i in range(2*n - 1):
            b[i+1] = a[i] + a[i + 2]
            if k < 2:
                b[0] = 1
                b[-1] = 1
        a = b
        k -= 1

if __name__ == "__main__":
    while True:
        inp = input("请输入基数： ").strip()
        if inp.isdigit():
            inp = int(inp)
            yh(inp)
            break
        else:
            print("输入错误！")
            
# def pas_triangles():
#     a = [1]
#     while True:
#         yield a
#         a = [sum(i) for i in zip([0] + a, a + [0])]
#
#
# if __name__ == "__main__":
#     g = pas_triangles()
#     for n in range(10):
#         print(next(g))
